version: '2'

services:
    web:
        image: nginx:latest
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/logs:/var/log/nginx/horario
            - ../.:/var/www/html
        ports:
            - "8080:80"
        networks:
            - local

    mariadb:
        build: mariadb/
        volumes:
            - database:/var/lib/mysql
        ports:
            - "3306:3306"
        env_file:
            - ./mariadb/.env
        networks:
            - local

    php:
        build: php/
        volumes:
            - ../.:/var/www/html
            - composer_cache:/var/www/.composer/cache
        networks:
            - local

volumes:
    database:
        driver: local
    composer_cache:
        driver: local

networks:
    local:
        driver: bridge