version: '2'

services:
    web:
        image: nginx:latest
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/logs:/var/log/nginx/horario
            - ../.:/var/www/html
        ports:
            - "80:80"
        networks:
            - local

    mariadb:
        build: mariadb/
        volumes:
            - database:/var/lib/mysql
        ports:
            - "3306:3306"
        env_file:
            - ./mariadb/.env
        networks:
            - local

    php:
        build: php/
        volumes:
            - ../.:/var/www/html
            - composer_cache:/var/www/.composer/cache
        networks:
            - local

    elasticsearch:
        build: elasticsearch/
        volumes:
            - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - elasticsearch:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - local

    kibana:
        build:  kibana/
        volumes:
            - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
        ports:
            - "81:5601"
        depends_on:
            - elasticsearch
        networks:
            - local

volumes:
    database:
        driver: local
    composer_cache:
        driver: local
    elasticsearch:
        driver: local

networks:
    local:
        driver: bridge